[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Ensure API routes work correctly
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/nextjs-server"
  status = 200
  force = true
